apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chinachu-pvc
  namespace: chinachu
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: "1Ti"
  selector:
    matchLabels:
      name: chinachu
